# PANDAS
This exercise is for you to practice your pandas skills! We will be using the [Games](https://www.kaggle.com/gutsyrobot/games-data/data) Dataset from Kaggle!.

#### Import pandas and read in the Games csv file and set it to a DataFrame called gms

In [1]:
# your code here-
import pandas as pd

gms = pd.read_csv('games.csv')

#### Check the head of the DataFrame.

In [2]:
# your code here-
gms.head()

       id       type  ... total_weights  average_weight
0   12333  boardgame  ...          2562          3.4785
1  120677  boardgame  ...          1423          3.8939
2  102794  boardgame  ...           777          3.7761
3   25613  boardgame  ...          1642          4.1590
4    3076  boardgame  ...          5213          3.2943

[5 rows x 20 columns]

####  Use .info() method to find out total number of entries in dataset

In [3]:
# your code here-
gms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81312 entries, 0 to 81311
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    81312 non-null  int64
 1   type                  81312 non-null  object
 2   name                  81271 non-null  object
 3   yearpublished         81309 non-null  float64
 4   minplayers            81309 non-null  float64
 5   maxplayers            81309 non-null  float64
 6   playingtime           81309 non-null  float64
 7   minplaytime           81309 non-null  float64
 8   maxplaytime           81309 non-null  float64
 9   minage                81309 non-null  float64
 10  users_rated           81312 non-null  int64
 11  average_rating        81312 non-null  float64
 12  bayes_average_rating  81312 non-null  float64
 13  total_owners          81312 non-null  int64
 14  total_traders         81312 non-null  int64
 15  total_wanters         81312 non-null  int64
 16  total_wishers         81312 non-null  int64
 17  total_comments        81312 non-null  int64
 18  total_weights         81312 non-null  int64
 19  average_weight        81312 non-null  float64
dtypes: float64(10), int64(8), object(2)
memory usage: 12.4+ MB

#### How many rows and columns are present in the dataset?

In [5]:
# your code here-
rows, columns = gms.shape

rows, columns

(81312, 20)

#### What is the highest number of comments received for a game?

In [6]:
# your code here-
max(gms.total_comments)

11798

#### What is the name of the game with id 1500?

In [11]:
# your code here-
gms.loc[gms.id == 1500,['name']].name

10592    Zocken
Name: name, dtype: object

#### Which games have received the least number of comments?

In [20]:
# your code here-
gms[gms.total_comments == min(gms.total_comments)][['name','total_comments']]

                                                    name  total_comments
13048                                         Looney Leo               0
13054                                               Dump               0
13068                                      Field of Fire               0
13095                                           Matheeno               0
13103  Auction America: The Trivia Game for Any Colle...               0
...                                                  ...             ...
81307                               Micro Rome: Aegyptus               0
81308  Trivial Pursuit: Marvel Cinematic Universe  Da...               0
81309                                          BEARanoia               0
81310                                            Freight               0
81311                                  Bingo Animal Kids               0

[29001 rows x 2 columns]

#### Which games have received the highest number of comments?¶

In [22]:
# your code here-
gms[gms.total_comments == max(gms.total_comments)][['name','total_comments']]

       name  total_comments
165   Catan           11798
1965  Catan           11798

#### How many unique games are there in the dataset?

In [26]:
# your code here-
gms.id.nunique()

79463

#### How many boardgames and boardgameexpansions are there in the dataset?

In [28]:
# your code here-
count_boardgames = len(gms[gms.type == 'boardgame'])
count_boardhameexpansions = len(gms[gms.type == 'boardgameexpansion'])

count_boardgames, count_boardhameexpansions

(70820, 10492)

#### What is the mean playin time for all games put together ?

In [30]:
# your code here-
gms.playingtime.mean(axis=0)

51.63478827682052

#### Is there a correlation between playing time and total comments for the games? hint:- Use the .corr() function

In [31]:
# your code here-
gms[['playingtime','total_comments']].corr()

#No correlation.

                playingtime  total_comments
playingtime        1.000000        0.020645
total_comments     0.020645        1.000000

# KEEP UP THE GOOD WORK!!!